name: Test Action

on:
  workflow_dispatch:

env:
  TEST_BRANCH: test-action

jobs:
  sync-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Create and Switch to Test Branch
        run: | 
          git checkout -b ${{ env.TEST_BRANCH }} || git checkout ${{ env.TEST_BRANCH }}
          git reset --hard origin/main
          git push origin ${{ env.TEST_BRANCH }} --force

      - name: Sync package.json version 🔄
        uses: richeyphu/sync-package-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.TEST_BRANCH }}
          skip-ci: true

      - name: Show updated package.json 📦
        run: cat package.json
